<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {
      font-family: Arial, sans-serif;
      color: #111827;
      background: #ffffff;
    }

    table.sheet {
      border-collapse: collapse;
      width: 100%;
    }

    col.wide { width: 210px; }
    col.medium { width: 145px; }
    col.narrow { width: 95px; }

    .title {
      font-size: 24px;
      font-weight: 700;
      color: #111827;
      background: #f8fafc;
      border: 1px solid #d1d5db;
      padding: 14px;
    }

    .subtitle {
      color: #4b5563;
      font-size: 12px;
      background: #f8fafc;
      border: 1px solid #d1d5db;
      padding: 10px;
    }

    .label {
      color: #374151;
      font-weight: 700;
      background: #eef2f7;
    }

    .accent {
      color: {{ $report['accent'] ?? '#2563eb' }};
      font-size: 22px;
      font-weight: 700;
      background: #ffffff;
    }

    .card-label {
      color: #111827;
      font-weight: 700;
      background: #eef2f7;
    }

    .section {
      color: #ffffff;
      font-size: 15px;
      font-weight: 700;
      background: {{ $report['accent'] ?? '#2563eb' }};
    }

    .description {
      color: #4b5563;
      background: #f8fafc;
      font-style: italic;
    }

    .head {
      color: #111827;
      font-weight: 700;
      background: #dbe4ef;
      text-align: center;
    }

    .cell {
      border: 1px solid #cbd5e1;
      padding: 8px;
      vertical-align: middle;
      mso-number-format: "\@";
    }

    .numeric {
      text-align: center;
      font-weight: 700;
    }

    .muted {
      color: #6b7280;
    }

    .spacer {
      height: 12px;
      background: #ffffff;
    }
  </style>
</head>
<body>
  @php
    $wideColumns = max(8, collect($report['sections'] ?? [])->map(fn($section) => count($section['columns'] ?? []))->max() ?: 0);
  @endphp

  <table class="sheet">
    <colgroup>
      <col class="wide">
      <col class="medium">
      <col class="medium">
      <col class="medium">
      <col class="medium">
      <col class="medium">
      <col class="medium">
      <col class="medium">
      <col class="narrow">
      <col class="narrow">
    </colgroup>

    <tr>
      <td colspan="{{ $wideColumns }}" class="title">{{ $report['title'] }}</td>
    </tr>
    <tr>
      <td colspan="{{ $wideColumns }}" class="subtitle">{{ $report['subtitle'] }}</td>
    </tr>
    <tr><td colspan="{{ $wideColumns }}" class="spacer"></td></tr>

    <tr>
      <td class="label cell">Generated At</td>
      <td class="cell">{{ $report['generated_at'] }}</td>
      <td class="label cell">Generated By</td>
      <td class="cell">{{ $report['generated_by'] }}</td>
      <td class="label cell">Reporting Period</td>
      <td class="cell">{{ $report['period'] ?? 'Current snapshot' }}</td>
      <td class="label cell">Report Type</td>
      <td class="cell">Detailed Executive Report</td>
    </tr>

    @if(!empty($report['insights']))
      <tr><td colspan="{{ $wideColumns }}" class="spacer"></td></tr>
      <tr>
        <td colspan="{{ $wideColumns }}" class="section cell">Executive Insights</td>
      </tr>
      <tr>
        @foreach($report['insights'] as $insight)
          <td class="card-label cell">{{ $insight['label'] }}</td>
        @endforeach
      </tr>
      <tr>
        @foreach($report['insights'] as $insight)
          <td class="accent cell numeric">{{ $insight['value'] }}</td>
        @endforeach
      </tr>
    @endif

    <tr><td colspan="{{ $wideColumns }}" class="spacer"></td></tr>
    <tr>
      <td colspan="{{ $wideColumns }}" class="section cell">Key Performance Indicators</td>
    </tr>
    <tr>
      @foreach($report['cards'] as $card)
        <td class="card-label cell">{{ $card['label'] }}</td>
      @endforeach
    </tr>
    <tr>
      @foreach($report['cards'] as $card)
        <td class="accent cell numeric">{{ $card['value'] }}</td>
      @endforeach
    </tr>
    <tr>
      @foreach($report['cards'] as $card)
        <td class="muted cell">{{ $card['note'] }}</td>
      @endforeach
    </tr>

    @foreach($report['sections'] as $section)
      <tr><td colspan="{{ $wideColumns }}" class="spacer"></td></tr>
      <tr>
        <td colspan="{{ $wideColumns }}" class="section cell">{{ $section['title'] }}</td>
      </tr>
      @if(!empty($section['description']))
        <tr>
          <td colspan="{{ $wideColumns }}" class="description cell">{{ $section['description'] }}</td>
        </tr>
      @endif
      <tr>
        @foreach($section['columns'] as $column)
          <td class="head cell">{{ $column }}</td>
        @endforeach
      </tr>
      @foreach($section['rows'] as $row)
        <tr>
          @foreach($row as $cell)
            <td class="cell">{{ $cell }}</td>
          @endforeach
        </tr>
      @endforeach
    @endforeach
  </table>
</body>
</html>
